export const PROVINCES = [
  "Azuay", "Bolívar", "Cañar", "Carchi", "Cotopaxi", "Chimborazo", "El Oro",
  "Esmeraldas", "Guayas", "Imbabura", "Loja", "Los Ríos", "Manabí",
  "Morona Santiago", "Napo", "Pastaza", "Pichincha", "Tungurahua",
  "Zamora Chinchipe", "Galápagos", "Sucumbíos", "Orellana",
  "Santo Domingo de los Tsáchilas", "Santa Elena",
];

export const CITIES_BY_PROVINCE = {
  "Azuay": ["Cuenca", "Gualaceo", "Paute", "Sigsig"],
  "Bolívar": ["Guaranda", "San Miguel", "Chillanes"],
  "Cañar": ["Azogues", "Biblián", "Cañar"],
  "Carchi": ["Tulcán", "San Gabriel", "Julio Andrade"],
  "Cotopaxi": ["Latacunga", "La Maná", "Salcedo", "Pujilí"],
  "Chimborazo": ["Riobamba", "Guano", "Chunchi"],
  "El Oro": ["Machala", "Pasaje", "Santa Rosa", "Huaquillas"],
  "Esmeraldas": ["Esmeraldas", "Atacames", "Quinindé"],
  "Guayas": ["Guayaquil", "Durán", "Milagro", "Daule", "Samborondón"],
  "Imbabura": ["Ibarra", "Otavalo", "Cotacachi", "Atuntaqui"],
  "Loja": ["Loja", "Catamayo", "Cariamanga"],
  "Los Ríos": ["Babahoyo", "Quevedo", "Ventanas"],
  "Manabí": ["Manta", "Portoviejo", "Chone", "Jipijapa"],
  "Morona Santiago": ["Macas", "Sucúa", "Gualaquiza"],
  "Napo": ["Tena", "Archidona"],
  "Pastaza": ["Puyo", "Mera"],
  "Pichincha": ["Quito", "Sangolquí", "Cayambe", "Machachi"],
  "Tungurahua": ["Ambato", "Baños", "Pelileo"],
  "Zamora Chinchipe": ["Zamora", "Yantzaza"],
  "Galápagos": ["Puerto Ayora", "Puerto Baquerizo Moreno"],
  "Sucumbíos": ["Nueva Loja (Lago Agrio)", "Shushufindi"],
  "Orellana": ["Puerto Francisco de Orellana (El Coca)"],
  "Santo Domingo de los Tsáchilas": ["Santo Domingo"],
  "Santa Elena": ["La Libertad", "Santa Elena", "Salinas"],
};
